### ISSUE TITLE
Forces a full update the crates.io index

### ISSUE THREAD

**Issue by Sytten** [cmyr/cargo-instruments#101]
Hi there!
Since rust 1.70 we are used to sparse update of the cargo registry and I am not sure why but running `cargo instrument` always seem to launch a full update which takes a very long time. Is that a byproduct of something else?
Thanks :)

**Comment by cmyr** [comment]
perhaps it's a consequence of us using an earlier version of the cargo lib here? Can update that and see if it fixes anything.

**Comment by cmyr** [comment]
actually this update already happened, I just haven't released a new version.

**Comment by cmyr** [comment]
Okay I've released 0.4.9, try updating and see if this problem is resolved?

**Comment by Sytten** [comment]
Solved, thanks!
