### ISSUE TITLE
Unable to parse lock file

### ISSUE THREAD

**Issue by jcholder-thoughtworks** [cmyr/cargo-instruments#11]
Howdy! I get the following error when I try to run `cargo instruments` (no arguments):

`Failed failed to parse lock file at: /[redacted but correct]/Cargo.lock`.

The `Cargo.lock` is freshly generated from a new project created a couple weeks ago.

[The full `Cargo.lock` file](https://gist.github.com/jcholder-thoughtworks/a8f4dd1386ebc8cd3f59988d96619070).

`cargo` version: `cargo 1.42.0-nightly (9d32b7b01 2020-01-26)`.
`rustc` version: `rustc 1.42.0-nightly (3761dcd34 2020-01-28)`.

Environment: macOS Mojave 10.14.6.

Initial guess is that the `cargo` crate in this crate needs to be updated to the current version, `0.42.0`.

Glad to provide additional info as needed. Thanks!

**Comment by jcholder-thoughtworks** [comment]
Heads up that `cargo` versions `0.36.0` and higher have breaking changes to the API.

**Comment by cmyr** [comment]
@jcholder-thoughtworks gotcha, thanks for opening the issue. To check my understanding, this is about the new lockfile format; the new `cargo` can work with the old format, but old `cargo` doesn't work with the new format?

Just want to make sure that updating cargo doesn't have any unintended consequences.

**Comment by cmyr** [comment]
@jcholder-thoughtworks I've just pushed a  patch would you like to try it out? You'll have to check it out locally and then do `cargo install --force --path=.` (assuming this is executed from the source directory). If this is working for you, I'll do a crates.io release.

**Comment by jcholder-thoughtworks** [comment]
@cmyr Success! Thanks!
