### ISSUE TITLE
Panic when custom templates are available with long paths

### ISSUE THREAD

**Issue by dvdplm** [cmyr/cargo-instruments#14]
When a custom template is present on the system `isntruments -s templates` will include it in the list twith the full path, e.g. `"~/Library/Application Support/Instruments/Templates/my-template-name.tracetemplate"` which breaks the assumption of max 64 chars long template names. The result is a panic when running `cargo instruments --list`.

**Comment by cmyr** [comment]
@dvdplm `0.3.1` is released, thanks for the issue!
