### ISSUE TITLE
Empty instrumentation data every other runs

### ISSUE THREAD

**Issue by nbigaouette** [cmyr/cargo-instruments#19]
I'm trying to debug a memory leak (see https://github.com/inejge/ldap3/issues/47) but I always need to run `cargo instruments` twice to get data in Instruments.

```sh
cargo instruments --limit 25000 --template Leaks --open
```

I think the problem happens when cargo rebuilds the binary before profiling it. This behaviour is consistent. I touch `src/main.rs` and run `cargo instruments`. The package gets rebuilt, but when Instruments launches, there is no profiling information. If I re-run `cargo instruments` I do get the profiling information.

~I will attach a screencast of the behaviour soon.~
Screencast: https://vimeo.com/422466785

**Comment by cmyr** [comment]
hmm, unless I'm misunderstanding something I'm not able to reproduce on 10.14.6:

![2020-05-26 15 30 16](https://user-images.githubusercontent.com/3330916/82942394-e58da500-9f65-11ea-9795-70a7baa2d002.gif)

**Comment by nbigaouette** [comment]
eurg... :(

I am using Catalina 10.15.4 (19E287) and Instruments 11.5 (11E608c).

I have fixed my memory leak so will not use Instruments for some time. I'll close this and reopen if I can get more details...
