### ISSUE TITLE
v0.3.3 tarball sha256 change?

### ISSUE THREAD

**Issue by carlocab** [cmyr/cargo-instruments#27]
I'm attempting to update Homebrew's version of Rust (https://github.com/Homebrew/homebrew-core/pull/66285).

While testing the new version, CI produced the following error:
```
==> brew install --build-from-source cargo-instruments
==> FAILED
==> Downloading https://github.com/cmyr/cargo-instruments/archive/v0.3.3.tar.gz
==> Downloading from https://codeload.github.com/cmyr/cargo-instruments/tar.gz/v0.3.3
Error: SHA256 mismatch
Expected: 7f6f095af8029e70cb0f7d52d1480fc827fe463362b30523fc3a221825b8f207
  Actual: 0da09ac0ebc78f60aa84abc7d67adb4e6eb30df692cb5c1d2d385b91e7163151
```

I can update the sha256 associated with cargo-instruments, but CI will come back to me with the following error:
```
cargo-instruments:
  * stable sha256 changed without the url/version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
```

Can I confirm that nothing is amiss here?

**Comment by cmyr** [comment]
nothing is amiss, I had tagged the wrong commit and didn't think anyone would notice. I can yank 0.3.3 and publish 0.3.4 shortly. Thanks for the issue!

**Comment by carlocab** [comment]
Sure, I figured it was something like that, but Homebrew CI wants me to be sure.

Publishing 0.34 would be ideal, as that would get CI to stop complaining at me.

Thanks again!

**Comment by cmyr** [comment]
@carlocab working on this now, should be published shortly.

**Comment by cmyr** [comment]
@carlocab should be good to go,  thanks!
