### ISSUE TITLE
how do I pass flags to the target binary

### ISSUE THREAD

**Issue by vim-zz** [cmyr/cargo-instruments#3]
I know of `--args`, but is there a way to pass flags to the target binary? 

For example, lets say my binary have `start` command and `--verbose` flag, so usually I run it using cargo:
```
$ cargo run -- start --verbose 
```

How should I do that with cargo instruments?

**Comment by cmyr** [comment]
@vim-zz it's currently a bit annoying, but you should be able to do,

```sh
$ cargo instruments --args '"-o --flag foo bar"'
```

Note that there are both single **and** double quotes around the args to be passed to the child.

**Comment by vim-zz** [comment]
great, good enough :-)
