### ISSUE TITLE
No `--test` flag

### ISSUE THREAD

**Issue by Schaeff** [cmyr/cargo-instruments#30]
I'm just curious why this tool does not have a `--test` flag to analyse tests?

Cheers!

**Comment by cmyr** [comment]
iirc I looked into this, but cargo builds tests differently and it would have been a reasonable amount of work to make it work. If you need to test a simple case it should be easy enough to just create an example binary and profile that?

**Comment by Schaeff** [comment]
It seems like tests are run in separate threads, with a smaller stack, which was causing the issue for me. That's why I wanted to see what was going on in the test itself. But yes, I found a workaround similar to what you suggested. Feel free to close this.

**Comment by cmyr** [comment]
If you're interested in writing a patch I'd be happy to merge but I don't think I'll get around to doing it myself anytime soon. Glad you figured out a workaround!

**Comment by matthiasgeihs** [comment]
Would also be interested in having this. Just a little less friction. [flamegraph](https://github.com/flamegraph-rs/flamegraph) was able to make it work, too. Maybe some hints can be drawn from their approach to it?
