### ISSUE TITLE
Inconsistent behaviour for the --template option

### ISSUE THREAD

**Issue by noirotm** [cmyr/cargo-instruments#38]
As of version 0.4.1, running `cargo instruments` without additional arguments yields the following output:

```
error: The following required arguments were not provided:
    --template <TEMPLATE>

USAGE:
    cargo instruments [FLAGS] [OPTIONS] --template <TEMPLATE> [ARGS]...

For more information try --help
```

Meanwhile, according to the README.md file, the expected behaviour is described as:

```
# omitting to provide a template will display an interactive menu
# to choose which template to use for profiling
$ cargo instruments
```

This seems to have been introduced in commit 4d3ebc4d.

**Comment by cmyr** [comment]
Oops, thanks, didn't catch that readme change.
