### ISSUE TITLE
Execute bench targets

### ISSUE THREAD

**Issue by michael-p** [cmyr/cargo-instruments#6]
It seems it is not possible to run `cargo instruments` on a benchmark target (i.e. what gets executed by `cargo bench`). I think this would be a very useful addition!

A more generic solution might be to make it possible to just pass in a path to an arbitrary executable file.

**Comment by cmyr** [comment]
I investigated benchmarks, and there were some problems. The main issue is that when you compile a benchmark target, the benchmark harness gets compiled in as well, which adds noise to the profile. I didn't dig into this too too much, so it's possible there's an easy solution, but it isn't totally obvoius.

**Comment by michael-p** [comment]
That's right, however, I'm not sure it's really a problem if the benchmark harness gets profiled as well since the overhead/noise there shouldn't be too high. `cargo flamegraph` seems to do it that way, see https://github.com/ferrous-systems/flamegraph/issues/1 and PR https://github.com/ferrous-systems/flamegraph/pull/29

**Comment by cmyr** [comment]
cool, that does look helpful.
