### ISSUE TITLE
Support --manifest-path?

### ISSUE THREAD

**Issue by helixbass** [cmyr/cargo-instruments#76]
Hi, what I'd like to do is to be able to profile running a Cargo-based project from a different working directory. From a little reading it looks like the standard argument to Cargo subcommands to achieve that is `--manifest-path ../path/to/Cargo.toml`, eg I'm able to do `cargo run --manifest-path ../path/to/Cargo.toml` from my desired working directory. So would it make sense for `cargo instruments` to also support being invoked with `--manifest-path` eg `cargo instruments --manifest-path ../path/to/Cargo.toml -t alloc`?

**Comment by cmyr** [comment]
This would be nice! I don't know if I'll have time to implement this myself in the near future, but if you'd like to prepare a PR I would be happy to review it!
